
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'ElementFooter': typeof import("../components/element/Footer.vue")['default']
    'ElementNavbar': typeof import("../components/element/Navbar.vue")['default']
    'SectionsAboutContent': typeof import("../components/sections/AboutContent.vue")['default']
    'SectionsCta': typeof import("../components/sections/Cta.vue")['default']
    'SectionsHeroSection': typeof import("../components/sections/HeroSection.vue")['default']
    'SectionsLoginSection': typeof import("../components/sections/LoginSection.vue")['default']
    'SectionsServices': typeof import("../components/sections/Services.vue")['default']
    'SectionsSocialProuf': typeof import("../components/sections/SocialProuf.vue")['default']
    'SectionsTaskForm': typeof import("../components/sections/TaskForm.vue")['default']
    'SectionsTaskList': typeof import("../components/sections/TaskList.vue")['default']
    'SectionsTaskManager': typeof import("../components/sections/TaskManager.vue")['default']
    'UiContainer': typeof import("../components/ui/Container.vue")['default']
    'UiLoginStatus': typeof import("../components/ui/LoginStatus.vue")['default']
    'UiToggleTheme': typeof import("../components/ui/ToggleTheme.vue")['default']
    'UnoIcon': typeof import("../node_modules/.pnpm/@unocss+nuxt@0.57.7_postcss@8.4.45_vite@5.4.3_webpack@5.94.0/node_modules/@unocss/nuxt/runtime/UnoIcon.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/.pnpm/@nuxt+image@1.8.0/node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
    'NuxtPicture': typeof import("../node_modules/.pnpm/@nuxt+image@1.8.0/node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
    'ColorScheme': typeof import("../node_modules/.pnpm/@nuxtjs+color-mode@3.4.4/node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'NuxtPage': typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyElementFooter': typeof import("../components/element/Footer.vue")['default']
    'LazyElementNavbar': typeof import("../components/element/Navbar.vue")['default']
    'LazySectionsAboutContent': typeof import("../components/sections/AboutContent.vue")['default']
    'LazySectionsCta': typeof import("../components/sections/Cta.vue")['default']
    'LazySectionsHeroSection': typeof import("../components/sections/HeroSection.vue")['default']
    'LazySectionsLoginSection': typeof import("../components/sections/LoginSection.vue")['default']
    'LazySectionsServices': typeof import("../components/sections/Services.vue")['default']
    'LazySectionsSocialProuf': typeof import("../components/sections/SocialProuf.vue")['default']
    'LazySectionsTaskForm': typeof import("../components/sections/TaskForm.vue")['default']
    'LazySectionsTaskList': typeof import("../components/sections/TaskList.vue")['default']
    'LazySectionsTaskManager': typeof import("../components/sections/TaskManager.vue")['default']
    'LazyUiContainer': typeof import("../components/ui/Container.vue")['default']
    'LazyUiLoginStatus': typeof import("../components/ui/LoginStatus.vue")['default']
    'LazyUiToggleTheme': typeof import("../components/ui/ToggleTheme.vue")['default']
    'LazyUnoIcon': typeof import("../node_modules/.pnpm/@unocss+nuxt@0.57.7_postcss@8.4.45_vite@5.4.3_webpack@5.94.0/node_modules/@unocss/nuxt/runtime/UnoIcon.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/.pnpm/@nuxt+image@1.8.0/node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
    'LazyNuxtPicture': typeof import("../node_modules/.pnpm/@nuxt+image@1.8.0/node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
    'LazyColorScheme': typeof import("../node_modules/.pnpm/@nuxtjs+color-mode@3.4.4/node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'LazyNuxtPage': typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const ElementFooter: typeof import("../components/element/Footer.vue")['default']
export const ElementNavbar: typeof import("../components/element/Navbar.vue")['default']
export const SectionsAboutContent: typeof import("../components/sections/AboutContent.vue")['default']
export const SectionsCta: typeof import("../components/sections/Cta.vue")['default']
export const SectionsHeroSection: typeof import("../components/sections/HeroSection.vue")['default']
export const SectionsLoginSection: typeof import("../components/sections/LoginSection.vue")['default']
export const SectionsServices: typeof import("../components/sections/Services.vue")['default']
export const SectionsSocialProuf: typeof import("../components/sections/SocialProuf.vue")['default']
export const SectionsTaskForm: typeof import("../components/sections/TaskForm.vue")['default']
export const SectionsTaskList: typeof import("../components/sections/TaskList.vue")['default']
export const SectionsTaskManager: typeof import("../components/sections/TaskManager.vue")['default']
export const UiContainer: typeof import("../components/ui/Container.vue")['default']
export const UiLoginStatus: typeof import("../components/ui/LoginStatus.vue")['default']
export const UiToggleTheme: typeof import("../components/ui/ToggleTheme.vue")['default']
export const UnoIcon: typeof import("../node_modules/.pnpm/@unocss+nuxt@0.57.7_postcss@8.4.45_vite@5.4.3_webpack@5.94.0/node_modules/@unocss/nuxt/runtime/UnoIcon.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/.pnpm/@nuxt+image@1.8.0/node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const NuxtPicture: typeof import("../node_modules/.pnpm/@nuxt+image@1.8.0/node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const ColorScheme: typeof import("../node_modules/.pnpm/@nuxtjs+color-mode@3.4.4/node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const NuxtPage: typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyElementFooter: typeof import("../components/element/Footer.vue")['default']
export const LazyElementNavbar: typeof import("../components/element/Navbar.vue")['default']
export const LazySectionsAboutContent: typeof import("../components/sections/AboutContent.vue")['default']
export const LazySectionsCta: typeof import("../components/sections/Cta.vue")['default']
export const LazySectionsHeroSection: typeof import("../components/sections/HeroSection.vue")['default']
export const LazySectionsLoginSection: typeof import("../components/sections/LoginSection.vue")['default']
export const LazySectionsServices: typeof import("../components/sections/Services.vue")['default']
export const LazySectionsSocialProuf: typeof import("../components/sections/SocialProuf.vue")['default']
export const LazySectionsTaskForm: typeof import("../components/sections/TaskForm.vue")['default']
export const LazySectionsTaskList: typeof import("../components/sections/TaskList.vue")['default']
export const LazySectionsTaskManager: typeof import("../components/sections/TaskManager.vue")['default']
export const LazyUiContainer: typeof import("../components/ui/Container.vue")['default']
export const LazyUiLoginStatus: typeof import("../components/ui/LoginStatus.vue")['default']
export const LazyUiToggleTheme: typeof import("../components/ui/ToggleTheme.vue")['default']
export const LazyUnoIcon: typeof import("../node_modules/.pnpm/@unocss+nuxt@0.57.7_postcss@8.4.45_vite@5.4.3_webpack@5.94.0/node_modules/@unocss/nuxt/runtime/UnoIcon.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/.pnpm/@nuxt+image@1.8.0/node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const LazyNuxtPicture: typeof import("../node_modules/.pnpm/@nuxt+image@1.8.0/node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const LazyColorScheme: typeof import("../node_modules/.pnpm/@nuxtjs+color-mode@3.4.4/node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const LazyNuxtPage: typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/.pnpm/nuxt@3.13.1_vite@5.4.3/node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
